#!/bin/zsh

source $DOTFILES_REPO/zsh/p10k.zsh
source $DOTFILES_REPO/zsh/npm_completion
source $DOTFILES_REPO/zsh/func
source $DOTFILES_REPO/zsh/aliases

if [[ -f $DOTFILES_REPO/zsh/.extra ]] {
 source $DOTFILES_REPO/zsh/.extra
}
